from django.urls import path

from service.views import (
    aprovar_orcamento,
    buscar_endereco_cep,
    cadastrar_cliente_orcamento,
    catalogo,
    concluir_orcamento,
    deletar_cliente,
    deletar_orcamento,
    deletar_produto,
    detalhe_orcamento,
    editar_produto,
    gerar_orcamento_pdf,
    inicio,
    listar_clientes,
    listar_leads,
    listar_orcamentos,
    nova_categoria,
    novo_lead,
    novo_orcamento,
    novo_produto,
    teste,
)

urlpatterns = [
    path("", inicio, name="inicio"),
    path("teste/", teste, name="teste"),
    path("leads/", listar_leads, name="leads"),
    path("catalogo/", catalogo, name="catalogo"),
    path("clientes/", listar_clientes, name="clientes"),
    path("clientes/novo/", novo_lead, name="novo_lead"),
    path("clientes/<int:pk>/deletar/", deletar_cliente, name="deletar_cliente"),
    path("catalogo/novo/", novo_produto, name="novo_produto"),
    path("catalogo/<int:pk>/editar/", editar_produto, name="editar_produto"),
    path("catalogo/<int:pk>/deletar/", deletar_produto, name="deletar_produto"),
    path("catalogo/categorias/nova/", nova_categoria, name="nova_categoria"),
    path("orcamentos/", listar_orcamentos, name="orcamentos"),
    path("orcamentos/novo/", novo_orcamento, name="novo_orcamento"),
    path("orcamentos/cep/<str:cep>/", buscar_endereco_cep, name="buscar_endereco_cep"),
    path("orcamentos/<int:pk>/", detalhe_orcamento, name="orcamento_detalhe"),
    path("orcamentos/<int:pk>/pdf/", gerar_orcamento_pdf, name="gerar_orcamento_pdf"),
    path("orcamentos/<int:pk>/concluir/", concluir_orcamento, name="concluir_orcamento"),
    path(
        "orcamentos/<int:pk>/cadastrar-cliente/",
        cadastrar_cliente_orcamento,
        name="cadastrar_cliente_orcamento",
    ),
    path("orcamentos/<int:pk>/aprovar/", aprovar_orcamento, name="aprovar_orcamento"),
    path("orcamentos/<int:pk>/deletar/", deletar_orcamento, name="deletar_orcamento"),
]
