# Generated by Django 6.0.4 on 2026-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_catalog',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(null=True)),
                ('formato', models.CharField(max_length=100, null=True)),
                ('tamanho', models.CharField(max_length=100, null=True)),
                ('largura', models.CharField(max_length=100, null=True)),
                ('comprimento', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
