# Generated by Django 6.0.4 on 2026-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service_catalog",
            name="tecido",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service_catalog",
            name="tempo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("valor", models.FloatField()),
                ("descricao", models.TextField(null=True)),
                ("quantidade", models.IntegerField()),
                (
                    "itens",
                    models.ManyToManyField(
                        related_name="orcamento_items",
                        to="service.service_catalog",
                    ),
                ),
            ],
            options={
                "db_table": "service_orçamento",
            },
        ),
    ]
