# Generated by Codex on 2026-05-05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0005_cliente_bairro_cliente_cep_cliente_cidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="status",
            field=models.CharField(
                choices=[
                    ("novo", "Novo"),
                    ("contatado", "Contatado"),
                    ("aguardando", "Aguardando"),
                    ("convertido", "Convertido"),
                ],
                default="novo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orcamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orcamento",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service_catalog",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service_catalog",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
