# Generated by Codex on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


def criar_categorias_por_tipo(apps, schema_editor):
    CategoriaCatalogo = apps.get_model("service", "CategoriaCatalogo")
    ServiceCatalog = apps.get_model("service", "Service_catalog")

    for item in ServiceCatalog.objects.exclude(tipo__isnull=True).exclude(tipo=""):
        categoria, _ = CategoriaCatalogo.objects.get_or_create(name=item.tipo)
        item.categoria = categoria
        item.save(update_fields=["categoria"])


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0006_dashboard_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCatalogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="service_catalog",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens",
                to="service.categoriacatalogo",
            ),
        ),
        migrations.RunPython(criar_categorias_por_tipo, migrations.RunPython.noop),
    ]
